defaults:
  - pipeline: local
  - _self_

seed: 42

data:
  delta_prefix:
    local: ".data/delta"
    databricks: "/Volumes/ml_artifacts"
  volume_name: "testing"

steps:
  prepare_data:
    step_name: "prepare_data"
    test_size: 0.2
    inputs: {}
    outputs:
      train_path:
        key: "train_path"
      test_path:
        key: "test_path"
      pipeline_run_id:
        key: "pipeline_run_id"
  train:
    step_name: "train"
    val_size: 0.2
    model_params:
      n_estimators: 50
      random_state: ${seed}
    inputs:
      train_path:
        key: "train_path"
        source_step: "prepare_data"
    outputs:
      train_run_id:
        key: "train_run_id"
  evaluate: 
    step_name: "evaluate"
    inputs:
      test_path:
        key: "test_path"
        source_step: "prepare_data"
      train_run_id:
        key: "train_run_id"
        source_step: "train"
    outputs: {}
  feature_importance:
    step_name: "feature_importance"
    n_repeats: 5
    inputs:
      train_path:
        key: "train_path"
        source_step: "prepare_data"
      train_run_id:
        key: "train_run_id"
        source_step: "train"
    outputs: {}
  model_qa:
    step_name: "model_qa"
    prod_model_uri: "models:/MyModel/Production" 
    inputs: {}
    outputs: {}

mlflow:
  log_datasets: true

