defaults:
  - experiment: local
  - _self_

seed: 42

steps:
  prepare_data:
    test_size: 0.2
  train:
    val_size: 0.2
    model_params:
      n_estimators: 50
      random_state: ${seed}
  evaluate: {}
  feature_importance:
    n_repeats: 5
  model_qa:
    prod_model_uri: "models:/MyModel/Production"  # Placeholder

